### PR TITLE
filters: fix checkbox not being clicked in mobile view

### LINKED ISSUE #267: frontsite: mobile search filters
- major: the filters cannot be selected: clicking on any of them dismisses the dialog but doesn’t actually select the filter
- minor: the filters button is hardly clickable, the hitbox only covers the text and not the whole highlighted element

### PR DESCRIPTION
**Pull request by KonstantinaStoikou**
Closes #267

### CODE REVIEW

**Review by ntarocco — APPROVED** [review]

**Review by jrcastro2 — APPROVED** [review]

File: src/lib/modules/SearchControls/SearchAggregationsMenu.js [hunk 1]
```diff
@@ -6,52 +6,22 @@ import { getSearchConfig } from '@config';
...
-
-  closeMenu = (e, elem) => {
-    this.setState({ menuOpen: false });
-  };
-
   render() {
     const { modelName } = this.props;
-    const { menuOpen } = this.state;
     const searchConfig = getSearchConfig(modelName);
-    // this element is needed to prevent the Dropdown menu
```
Comment (kprzerwa) [inline src/lib/modules/SearchControls/SearchAggregationsMenu.js:27]: did you check if this is still the issue after your change? 
Screenshot 2021-01-06 at 15 09 17
the problem was that when you clicked on 'Literature types" or any other category of filters the whole menu was collapsing, and choosing a filter was not possible

Comment (KonstantinaStoikou) [reply src/lib/modules/SearchControls/SearchAggregationsMenu.js:27]: this problem is fixed

**Review by kprzerwa — APPROVED** [review]
