### PR TITLE
backoffice: fix the workflow of LiteratureRequest

### LINKED ISSUE #290: backoffice: literature request workflow
* on the "Select provider" step:
  * both searchbars do not include the searched text in the query url (add a method in the query builder)
  * when clicking on a result of the acquisition order searchbar, it should bind the record to the request and proceed to the next step (as for the ILL loan). Currently it acts as an `ESSelector` form field -> this happens when trying to add a provider in an already accepted request because it throws a server error and hangs (because demo requests from cli don't have a provider assigned to them)
  * the user is asked to select an existing order/loan or to create a new one. The creation button does not automatically link the newly created record to the request (the button is merely a link to the corresponding creation form)
    * what should happen: the librarian clicks on either create create button, fill the form, submit it, should be redirected to the request details page and should observe that the request has progressed to the next step
    * alternatively, open the creation form in a new page so that the user can come back to their request (less good but easier to implement)

See also inveniosoftware/invenio-app-ils#973

### PR DESCRIPTION
**Pull request by KonstantinaStoikou**
- redirect order and borrowing request forms to literature request form
- add function `listWithPendingStatus` to be used in Provider's ESSelector because previously it displayed all results with `status=PENDING` without taking into account the search query
Closes #290

### CODE REVIEW

File: src/lib/api/acquisition/order.js [hunk 1]
```diff
@@ -111,6 +120,7 @@ export const orderApi = {
   create: create,
   update: update,
   list: list,
+  listWithPendingStatus: listWithPendingStatus,
```
Comment (FlorianCassayre) [inline src/lib/api/acquisition/order.js:123]: (minor) I'm in favour of using the request builder for that; say `withQuery` that allows to enter a free text query.

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js [hunk 2]
```diff
@@ -65,7 +65,7 @@ export class OrderEditor extends Component {
     const request = _get(this.props, 'location.state', null);
     if (!request) return null;
     return {
-      documentRequestPid: request.pid,
+      documentRequestPid: request.id,
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js:68]: did you mean `request.metadata.pid`? `.id` is inconsistent with all the other record types we have

Comment (FlorianCassayre) [inline src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js:68]: Question: what does it change?

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js [hunk 3]
```diff
@@ -100,10 +104,25 @@ export class OrderForm extends Component {
...
+    const order = getIn(response, 'data');
+    const documentRequestPid = _get(
+      this.props,
+      'data.documentRequestPid',
+      null
     );
+    if (documentRequestPid) {
+      await documentRequestApi.addProvider(documentRequestPid, {
+        physical_item_provider: {
+          pid: order.pid,
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:117]: `order.metadata.pid` (verify if it works please), we try to abandon the `record.pid` because it is inconsistent with the objects structures, we introduced it at some point in the serializers, but it is confusing IMO

File: src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentEditor.js [hunk 4]
```diff
@@ -37,7 +37,7 @@ export class DocumentEditor extends Component {
     const request = _get(this.props, 'location.state', null);
     if (!request) return null;
     return {
-      documentRequestPid: request.pid,
+      documentRequestPid: request.id,
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentEditor.js:40]: `documentRequestPid: request.metadata.pid`, as above, to be verified if it works

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js [hunk 5]
```diff
@@ -82,14 +82,7 @@ class AcqProvider extends Component {
...
               onSelectResult={this.onSelectResult}
-              query={() =>
-                orderApi.list(
-                  orderApi
-                    .query()
-                    .withState('PENDING')
-                    .qs()
-                )
-              }
+              query={orderApi.listWithPendingStatus}
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js:85]: I'm not sure if supplying only the `PENDING` ones will be OK in this case. @topless @ntarocco is there any use case we would like to connect orders/ILLs in the states different than `PENDING`?

File: src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestEditor.js [hunk 6]
```diff
@@ -36,6 +36,7 @@ export class BorrowingRequestEditor extends Component {
     } = this.props;
     if (!request) return null;
     return {
+      documentRequestPid: request.id,
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestEditor.js:39]: `request.metadata.pid` as in the comments above

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js [hunk 7]
```diff
@@ -100,10 +104,25 @@ export class OrderForm extends Component {
     return orderApi.update(pid, data);
   };
 
-  successCallback = response => {
-    goTo(
-      AcquisitionRoutes.orderDetailsFor(getIn(response, 'data.metadata.pid'))
+  successCallback = async response => {
```
Comment (FlorianCassayre) [inline src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:107]: Good job, great UX design.
That said I'm not 100% sure about making the request in the form submit callback. For instance, how should we handle exception? (currently not implemented as fair as I'm aware)

File: src/lib/api/acquisition/order.js (hunk 1 above)
Comment (KonstantinaStoikou) [reply src/lib/api/acquisition/order.js:123]: It wouldn't work with `withQuery` because we would need to pass arguments in the call here https://github.com/inveniosoftware/react-invenio-app-ils/blob/7574e2d949f18d414100d1dfcecc5b1e4bd6dd86/src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js#L85
and in `HitsSearch.js` we need to pass only the reference to the function if we want the query string to be taken into account https://github.com/inveniosoftware/react-invenio-app-ils/blob/64754f29ac5dcf7876b4d06095e8cca76379cc72/src/lib/modules/ESSelector/HitsSearch.js#L81

Comment (FlorianCassayre) [reply src/lib/api/acquisition/order.js:123]: Yes, in this case you can always create an anonymous function:
```javascript
query={
  q => orderApi
        .query()
        .withStatus('PENDING')
        .withQuery(q) // Pass the argument
        .qs()
}
```
Or, better create a function in the class and reference it.

Comment (KonstantinaStoikou) [reply src/lib/api/acquisition/order.js:123]: The query builder will build the query (`queryString` + `SearchCriteria`) but we still need to pass it as an argument in the `list` function to create the url and make the request.

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js (hunk 2 above)
Comment (KonstantinaStoikou) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js]: I intentionally changed it to `id` because yesterday I tested it and the `pid` was sometimes undefined but the `id` had a value but I probably did something wrong because now that I tested it it's working fine.

Comment (KonstantinaStoikou) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js]: Answered above.

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js (hunk 7 above)
Comment (KonstantinaStoikou) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:107]: If you are talking about exceptions that might occur during adding the provider, I think we can add an action to dispatch an error message instead of directly calling the `addProvider` from the api in the callback.

File: src/lib/api/acquisition/order.js (hunk 1 above)
Comment (FlorianCassayre) [reply src/lib/api/acquisition/order.js:123]: Sorry you're right I forgot it returned an url instead of an http request.

Comment (kprzerwa) [reply src/lib/api/acquisition/order.js:123]: you could still use the query builder to build the url in borrowingRequest.js instead of hardcoding it

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js (hunk 7 above)
Comment (ntarocco) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:107]: Question for reviewers: I am wondering if this should be done on the backend. After a record creation (signal), update the document request...

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js (hunk 5 above)
Comment (ntarocco) [reply src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js:85]: Maybe it will be safer to get the orders that do not have yet a `document_request_pid`, independently of the state.
Imagine the scenario where the librarian will not follow the workflow and:
1. see the doc request
2. go to the order page and create a new order
3. come back to the doc request and want to attach it.

WDYT?

File: src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js (hunk 7 above)
Comment (kprzerwa) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:107]: I'm not sure why it was not done in the backend in the first place. at this point I would say to ticketize it for refatoring @ntarocco WDYT?

Comment (ntarocco) [reply src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js:107]: It is harder than I thought. Let's keep it like this.

**Review by kprzerwa — APPROVED** [review]

File: src/lib/api/acquisition/order.js [hunk 8]
```diff
@@ -31,6 +32,22 @@ const list = async query => {
   return response;
 };
 
+const listWithPendingStatus = async query => {
+  const searchCriteria = orderApi
+    .query()
+    .withState(
+      `(${invenioConfig.ILL_BORROWING_REQUESTS.pendingStatuses.join(' OR ')})`
```
Comment (kprzerwa) [inline src/lib/api/acquisition/order.js:39]: 👀  please change to acq states

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js (hunk 5 above)
Comment (KonstantinaStoikou) [reply src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js:85]: There is no `document_request_pid` in the order and there is no connection between the order and the document request from the order's side.
