### PR TITLE
[MERGE WITH Backend] New literature request form and fixes

### LINKED ISSUE #334: New literature request CRUD
Librarian should be able to CRUD (Create/Update/Delete) new literature request.

- [x] create a new edit page with the UI web form in the backoffice for new literature request
- [x] make sure backend permission are correct: librarian can read/list/edit/create/delete, patron can only read/list its own requests (not all) 
- [x] **optional** maybe a good idea to add the Steps in the UI on the top as for ILL/ACQ

Make sure that the librarian can select/change which patron created the request and attach/replace document, ILL/ACQ.

### PR DESCRIPTION
**Pull request by ntarocco**
- Add new RJSF widgets for form input that reference other records
- Improve error and success notifications with RSJForms
- Finalize form for new literature requests
- Partially redesign the details view to have it more similar to other
  backoffice pages
- partially closes #334

**WARNING** To be merged with backend https://github.com/inveniosoftware/invenio-app-ils/pull/1034

Screenshot 2021-02-14 at 17 48 40

Screenshot 2021-02-14 at 17 49 03

Screenshot 2021-02-14 at 17 47 28

### CODE REVIEW

File: src/lib/forms/rjsf/widgets/RJSFESSelector.js [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+      });
+
+      const response = await this.cancellableFetchData.promise;
+      const results = response.data.hits.map((hit) =>
+        apiQueryResponseSerializer(hit)
+      );
+
+      if (!required) {
+        // add an empty element at the beginning so that if it is not required, you can select nothing
+        results.unshift({ key: '', value: undefined, text: '' });
```
Comment (jrcastro2) [inline src/lib/forms/rjsf/widgets/RJSFESSelector.js:84]:
```suggestion
        results.unshift({ key: '', value: undefined, text: '-' });
```
Comment: IMHO if it's empty it's harder to recognise you can actually select it, with the hyphen maybe it's more user-friendly. WDYT?

File: src/lib/forms/rjsf/widgets/RJSFESSelector.js [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+        value={value}
+        required={required}
+        autoFocus={autofocus}
+        readOnly={readonly}
+        placeholder={placeholder}
+        onChange={this.handleChange}
+        onSearchChange={_debounce(this.handleSearchChange, debounceDelay)}
+        disabled={isLoading}
+        loading={isLoading}
+        noResultsMessage={error ? error : 'No results found'}
```
Comment (jrcastro2) [inline src/lib/forms/rjsf/widgets/RJSFESSelector.js:134]: Minor: Could we add and pass an `icon` prop? For some fields it may be useful, like for the patron, where we can add the search icon.
```diff
+        icon={icon}
```
image

File: src/lib/forms/rjsf/widgets/RJSFVocabulary.js [hunk 3]
```diff
@@ -34,10 +44,24 @@ export class RJSFVocabulary extends Component {
...
+
       const response = await this.cancellableFetchData.promise;
       const results = response.data.hits.map((hit) => this.serializer(hit));
+      if (!results) {
+        throw Error('No results? This is probably a misconfiguration.');
+      }
+
+      if (!required) {
+        // add an empty element at the beginning so that if it is not required, you can select nothing
+        results.unshift({ key: '', value: undefined, text: '' });
```
Comment (jrcastro2) [inline src/lib/forms/rjsf/widgets/RJSFVocabulary.js:62]:
```suggestion
        results.unshift({ key: '', value: undefined, text: '-' });
```
Comment: Same comment as above (if you agree).

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/uiSchema.js [hunk 4]
```diff
@@ -31,10 +43,15 @@ export const uiSchema = (title) => ({
       'custom:divider': 16,
     },
     {
-      state: 4,
-      reject_reason: 4,
-      document_pid: 4,
-      internal_note: 4,
+      state: 8,
+      decline_reason: 7,
```
Comment (jrcastro2) [inline src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/uiSchema.js:47]:
```suggestion
      decline_reason: 8,
```

**Review by jrcastro2 — APPROVED** [review]

**Review by KonstantinaStoikou — APPROVED** [review]
It would be nice if the literature request details were inside a container (like in document details) instead of fully expanding to the sides of the screen. Also since document pid is not required in the form maybe it should have an empty option in case we want to remove it.

**Comment by ntarocco** [comment]
> It would be nice if the literature request details were inside a container (like in document details) instead of fully expanding to the sides of the screen. Also since document pid is not required in the form maybe it should have an empty option in case we want to remove it.

Makes sense for the container! Is it ok if I do it in the next one since I will have to work on the layout?

For the document pid, it is already the case, just not very visible, that's why Javier was suggesting to add `-` instead.
I was actually thinking to remove from the form the `document_pid` field since it can be changed from the details page...

File: src/lib/forms/rjsf/widgets/RJSFReferencedDocument.js [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+  query = async (searchQuery) => await documentApi.list(searchQuery);
+
+  render() {
+    const { options } = this.props;
+    return (
+      <RJSFESSelector
+        {...this.props}
+        options={{
+          apiGetByValue: async (value) => await documentApi.get(value),
```
Comment (kprzerwa) [inline src/lib/forms/rjsf/widgets/RJSFReferencedDocument.js:37]: that's neat

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js [hunk 6]
```diff
@@ -0,0 +1,133 @@
+import { documentApi } from '@api/documents';
+import { ESSelectorModal } from '@modules/ESSelector';
+import { serializeDocument } from '@modules/ESSelector/serializer';
+import get from 'lodash/get';
+import PropTypes from 'prop-types';
+import React from 'react';
+import { Confirm, Dropdown } from 'semantic-ui-react';
+
+export class DeclineAction extends React.Component {
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js:9]: nit: I find it a bit inconsistent that we have Action which is a component, not redux action (in the name)

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+        confirmModalOpened: true,
+      });
+    } else {
+      throw new Error(`Invalid decline type: ${value}`);
+    }
+  };
+
+  renderOptions() {
+    const options = [
+      {
```
Comment (kprzerwa) [inline src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js:49]: shouldn't this be a vocab ?

**Review by kprzerwa — APPROVED** [review]

**Review by kprzerwa — COMMENTED** [review]
In the form you could replace labels `Document PID - > Document` and `Patron PID` to `Patron`

File: src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js (hunk 7 above)
Comment (ntarocco) [reply src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DeclineAction.js:49]: No, it is not, it is an hardcoded enum. This is because the system is doing different things based on that value, it is affecting behavior.
