### PR TITLE
backoffice: fix date picker for loans and add date sorting

### LINKED ISSUE #404: Loans Date search broken
Package version (if known): 29

## Describe the bug
Loans Date search doesn't work properly

## Steps to Reproduce
There are multiple issues:
1. In Loans search page, the date filter currently allows only one field (From or To) to be entered, 
2. Clicking on x doesn't clear the field and typing keyboard DELETE key doesn't clear it - only works sometimes 
3. The results are erratic - see screenshot

### PR DESCRIPTION
**Pull request by KonstantinaStoikou**
Closes #404

### CODE REVIEW

File: src/lib/pages/backoffice/Loan/LoanSearch/SearchDateRange.js [hunk 1]
```diff
@@ -20,17 +19,10 @@ export class _SearchDateRange extends Component {
...
-   */
   onDateChange = (newFilter) => {
     const { currentQueryState, updateQueryState } = this.props;
-    const [name, value] = newFilter;
-    const filters = currentQueryState.filters.filter(
-      (filter) => filter[0] === name
-    );
-    if (!_isEmpty(value)) filters.push(newFilter);
+    const filters = currentQueryState.filters;
+    filters.push(newFilter);
```
Comment (ntarocco) [inline src/lib/pages/backoffice/Loan/LoanSearch/SearchDateRange.js:25]: This was tricky when we implemented it long time ago, I hope you were able to test any possible scenario (only one date input, or both, or remove them)

**Review by ntarocco — APPROVED** [review]

File: src/lib/pages/backoffice/Loan/LoanSearch/SearchDateRange.js (hunk 1 above)
Comment (KonstantinaStoikou) [reply src/lib/pages/backoffice/Loan/LoanSearch/SearchDateRange.js:25]: I tested it, also with a combination of other facets and it seemed to work fine.
