### PR TITLE
search: improve searchbar

### LINKED ISSUE #235: Backoffice: in LoanDetails Available physical copies search bar
Package version (if known): react-ils1.0.0-alpha.13

## Describe the bug
This search bar should serve the purpose of checking out a physical copy for our loan. The physical copy **has** to be from the document attached to the loan.

## Steps to Reproduce
1. https://dev-cds-ils.web.cern.ch/backoffice/loans/hrckh-k2220
2. Try to search for something in the search bar

## Expected behavior
1. If the barcode of the physical item can be loaned and belongs to the document, check it out.
2. It should support the `onPaste` handler since its intended to work with the barcode scanner

## Screenshots (if applicable)
Screenshot 2020-10-12 at 11 43 03 AM

### LINKED ISSUE #264: ILS Search bar - paste event broken
when pasting in document details search bar or homepage search the text is duplicated

### PR DESCRIPTION
**Pull request by FlorianCassayre**
* implement loan checkout workflow with barcode reader (closes #235)
* disable search on paste on frontsite (closes #264)

Loan checkout behavior that this PR implements:
* if the librarian scans an item and all the conditions are met for this item to be loaned, then the item is shown in the search results and a checkout action is automatically triggered (as opposed to searching for an item and then clicking on the button)
* the same happens when a barcode is manually typed and submitted (= clicking on the search button or hitting enter)
* an information message indicates the existence of this behavior when it is applicable
* when typing, the search results are updated accordingly (filtered, since no request is performed). That is, all the items having a barcode starting with the query will be shown

Capture d’écran de 2020-11-06 09-35-54

### CODE REVIEW

**Comment by kprzerwa** [comment]
> * the search results are not updated when typing, only after submitting
>   
>   * should this be modified?

no this is desired behaviour, otherwise we are performing a request on every key stroke

lets discuss the rest IRL

**Review by kprzerwa — COMMENTED** [review]
to discuss

**Review by kprzerwa — COMMENTED** [review]
after discussion: it is missing a message telling the user what kind of behaviour to expect on paste/scan

**Comment by FlorianCassayre** [comment]
I think I did (cf. blue message on screenshot).

File: src/lib/components/SearchBar/SearchBarILS.js [hunk 1]
```diff
@@ -65,13 +67,15 @@ SearchBarILS.propTypes = {
...
   onPasteHandler: PropTypes.func,
   onSearchHandler: PropTypes.func.isRequired,
+  onChangeHandler: PropTypes.func,
   placeholder: PropTypes.string,
   className: PropTypes.string,
 };
 
 SearchBarILS.defaultProps = {
   onKeyPressHandler: null,
   onPasteHandler: null,
```
Comment (KonstantinaStoikou) [inline src/lib/components/SearchBar/SearchBarILS.js:77]: if you set the default onPasteHandler as `() => {}` instead of setting it in the components that use the SearchBarILS?

Comment (FlorianCassayre) [reply src/lib/components/SearchBar/SearchBarILS.js:77]: `SearchBarILS` provides a default handler if none is defined, and it's the one that trigger search when <kbd>Enter</kbd> is pressed. Could be refactored to have an additional props that controls this (ie. `isSearchOnPaste`).

**Comment by kprzerwa** [comment]
> I did include it (cf. blue message on screenshot), unless I misunderstood something.

no I just added that comment to highlight the fact that we discussed it, you didn't miss anything :)

**Review by kprzerwa — APPROVED** [review]
